apiVersion : apps/v1
kind: Deployment
metadata:
  name: image1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image1
  template:
    metadata:
      labels:
        app: image1 
    spec:
      containers:
        - name: image1 
          image: mycontainerregistry898.azurecr.io/pipelinesjavascriptdocker:58
          ports:
          - containerPort: 8080
